#define FORWARD_POINT_LIGHT_COUNT 8
#define FORWARD_SPOT_LIGHT_COUNT 8

#define DEFERRED_POINT_LIGHT_COUNT 32
#define DEFERRED_SPOT_LIGHT_COUNT 16

#define WINDOW_RESOLUTION_X 1920
#define WINDOW_RESOLUTION_Y 1080